### ISSUE TITLE
Is there anyway to create inter-connections within each layer?

### ISSUE THREAD

**Issue by zhouyisu** [battlesnake/neural#3]
Hi, I am wondering if it is possible to indicate inter-connections within each layer? In my discipline, it is common that x1 and x2 are correlated (a two-way connector). Is there any option/tweak to use based on current solution?

**Comment by battlesnake** [comment]
Look at the `\link` macro in the XOR example, you should be able to use that to link any two nodes in the graph

**Comment by zhouyisu** [comment]
Thanks. I missed that one. Please consider this as closed.
