### ISSUE TITLE
\linklayers doesn't work when exclude is used

### ISSUE THREAD

**Issue by TorbjornT** [battlesnake/neural#4]
From the code (https://github.com/battlesnake/neural/blob/master/neuralnetwork.sty#L208) I had expected that `\linklayers` would work even if `exclude` was used for one of the layers. However, that is not the case, the code below throws  `! Package pgf Error: No shape named L0-2 is known.`

```
\documentclass[border=5mm]{standalone}
\usepackage{neuralnetwork}
\begin{document}
\begin{neuralnetwork}
  \inputlayer[count=3,exclude={2},bias=false,]
  \hiddenlayer[count=1,bias=false]
     \linklayers
\end{neuralnetwork}
\end{document}
```

(I came across this when writing an answer for https://tex.stackexchange.com/questions/406167/. )

**Comment by battlesnake** [comment]
Hi,

While it's great to see what people are doing with my package, I haven't done any LaTeX stuff for several years now, so I'm unable to fix it myself.

One possible solution would be to modify the "exclude" handling so it creates invisible nodes in the position of the excluded one.  This creates the problem then that `\linklayers` will probably draw visible edges to those nodes though.  Adding extra properties to indicate whether a node is excluded or not, which can then be checked later by `linklayers` would solve this though.

**Comment by TorbjornT** [comment]
Actually, I just realized I had misread the code, failing to notice the `not from`/`not to` keys. Sorry about that. 

On the other hand, those keys doesn't work, because in `\linklayers` you do

```
l.206  \foreach \lastnode in {...}
l.207    \foreach \thisnode in {...}
```

but a couple of lines later you say

```
l.211 \if \nn@excluded \nn@lastnode ... % should be \lastnode
l.213 \if \nn@excluded \nn@thisnode ... % should be \thisnode
```

As a result, if one does `\linklayers[not from={2}]`, an undefined control sequence error is thrown due to `\nn@lastnode`. 

Fixing that would close this issue for me, would be great if you could do it and upload a new version to CTAN.

**Comment by battlesnake** [comment]
Ok - if you have a fix, please could you submit a pull-request with it?  I haven't done any low-level LaTeX for several years now so I'd rather someone more familiar made the fix so I don't break anything.
